language: python

python:
  - "3.6"

matrix:
  include:
    - python: 3.7
      dist: xenial  # required for Python 3.7 (travis-ci/travis-ci#9069)
  
env:
  global:
    - SECRET_KEY=abcdefghijklmnopqrstuvwxyz0123456789
    - DATABASE_URL=sqlite:///db.sqlite3

install:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - python manage.py test -v2 -k
