# Generated by Django 2.1.1 on 2018-09-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='protocol',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.BinaryField(),
        ),
    ]
