# Generated by Django 2.1.1 on 2018-09-14 12:29

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=30, verbose_name='FontAwesome Icon Class')),
                ('colour', models.CharField(max_length=30, verbose_name='Bootstrap Colour Class')),
                ('text', markdownx.models.MarkdownxField(verbose_name='Text (MarkDown syntax allowed)')),
            ],
        ),
    ]
