# Generated by Django 2.1.1 on 2018-09-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frontitem',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='frontitem',
            name='label',
            field=models.CharField(default='', max_length=50, verbose_name='Label'),
        ),
        migrations.AddField(
            model_name='frontitem',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
    ]
