# Generated by Django 2.1.1 on 2018-09-20 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fseid', models.BigIntegerField(blank=True, verbose_name='FSEconomy User ID')),
                ('key', models.CharField(blank=True, default='', max_length=20, verbose_name='FSEconomy Access Key')),
                ('avatar', models.URLField(blank=True, max_length=255, verbose_name='Avatar URL')),
                ('valid', models.BooleanField(default=False, verbose_name='Validated Profile')),
                ('validated', models.DateTimeField(blank=True, null=True, verbose_name='Validation timestamp')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Validation token')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Account created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Account updated')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
