# Generated by Django 2.1.1 on 2018-09-14 14:45

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20180914_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='Label')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Time Stamp')),
                ('text', markdownx.models.MarkdownxField(verbose_name='Text (MarkDown syntax allowed')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
