# Generated by Django 2.1.1 on 2018-09-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_newsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='Item is public'),
        ),
    ]
