# Generated by Django 2.1.1 on 2018-09-14 14:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_newsitem_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 14, 14, 49, 29, 42775, tzinfo=utc), verbose_name='Time Stamp'),
        ),
    ]
