# Generated by Django 2.1.1 on 2018-09-14 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20180914_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time Stamp'),
        ),
    ]
