# Generated by Django 2.1.1 on 2018-09-15 05:13

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20180914_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=100, verbose_name='Content Identifier')),
                ('text', markdownx.models.MarkdownxField(verbose_name='Text (MarkDown syntax allowed')),
            ],
        ),
    ]
